#!/usr/bin/env bash

# Check if the required number of parameters is provided
if [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Extract the parameters
file="$1"
ip="$2"
user="$3"
key="$4"

# Transfer the file using scp
scp -i "$key" -o StrictHostKeyChecking=no "$file" "$user"@"$ip":~/

# Check the exit status of the scp command
if [ $? -eq 0 ]; then
    echo "File transferred successfully."
else
    echo "File transfer failed."
fi
