#!/bin/bash

# Backup the original /etc/hosts file
sudo cp /etc/hosts /etc/hosts.backup

# Update /etc/hosts file
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

# Flush DNS cache
sudo systemctl restart systemd-resolved.service

echo "Configuration completed."
